page({
  data:{
    autoplay:true,
    interval:2000,
    duration:1000,
    circular:true,
    imgUrl:[
      "../img/ban1.jpg",
      "../img/ban2.jpg",
      "../img/ban3.jpg",
      "../img/ban4.jpg",
      "../img/ban5.jpg"
    ]
  }
})